// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Poll struct {
	Question string       `json:"question"`
	AnswerA  *VotedAnswer `json:"answerA"`
	AnswerB  *VotedAnswer `json:"answerB"`
}

type VotedAnswer struct {
	Answer string `json:"answer"`
	Votes  *int   `json:"votes"`
}
